/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:81eb0707-da27-4ea0-ae16-319e859edfe0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZrQyMClq2",
    "aws_user_pools_web_client_id": "lgd4dd1ikus1il5je8mmtmruc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6hir3trekvbnhl2aq32xlmsdum.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
